default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: blogs_dev

test:
  <<: *default
  database: blogs_test

production:
  <<: *default
  database: blogs
